spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
//C:\Users\flenn\medical-service\src\main\java\com\github\Alina1999mikh\medicalservice\service
  datasource:
    url: jdbc:postgresql://localhost:6223/medicalBase
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none